/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_httc_scan_jni_HttcSdk */

#ifndef _Included_com_httc_scan_jni_HttcSdk
#define _Included_com_httc_scan_jni_HttcSdk
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_httc_scan_jni_HttcSdk
	 * Method:    getFileMd5
	 * Signature: (Ljava/lang/String;)Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_com_httc_scan_jni_HttcSdk_getFileMd5
		(JNIEnv *, jclass, jstring);

	/*
	 * Class:     com_httc_scan_jni_HttcSdk
	 * Method:    getFileSha256
	 * Signature: (Ljava/lang/String;)Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_com_httc_scan_jni_HttcSdk_getFileSha256
		(JNIEnv *, jclass, jstring);
	/*
	 * Class:     com_httc_scan_jni_HttcSdk
	 * Method:    getFileSm3
	 * Signature: (Ljava/lang/String;)Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_com_httc_scan_jni_HttcSdk_getFileSm3
		(JNIEnv *, jclass, jstring);
#ifdef __cplusplus
}
#endif
#endif

